### ISSUE TITLE
Crash on dedicated server when reloading

### ISSUE THREAD

**Issue by Bodou2004** [zaeonNineZero/CGM-Expander-Fork#4]
I am experiencing a consistent server crash when using the reload mechanic of MrCrayfish's Gun Mod (and its expansions) on a dedicated server. The crash occurs specifically when a player reloads a weapon, and it prevents the server from starting again until the mod is removed.

>Start a dedicated server with the mod and its expansions installed.
>Join the server and obtain any firearm from the mod.
>Attempt to reload the weapon
>The server crashes immediately with the error below. After the crash, the server cannot be started again unless the gun mod files are removed.

[crash-2025-12-04_00.54.26-server.txt](https://github.com/user-attachments/files/23919318/crash-2025-12-04_00.54.26-server.txt)

<img width="670" height="327" alt="Image" src="https://github.com/user-attachments/assets/377e8a67-736c-41a8-a192-62a383275510" />

**Comment by zaeonNineZero** [comment]
Much like issue #3 , this is another case of the LocalPlayer class being loaded server-side:
`java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/LocalPlayer for invalid dist DEDICATED_SERVER`

The offending class is `guns.common.ReloadTracker`, in the method `increaseAmmo`, which is directly calling the client-side class `GunRenderingHandler`. I'm actively working on switching this call to a network message, which should fix the issue.

**Comment by Bodou2004** [comment]
The error has stopped occurring! I compiled the mod, but I see you forgot to upload it!

**Comment by zaeonNineZero** [comment]
Switched the `GunRenderingHandler` call to a network message, and tested it successfully on my test server setup.

Also, thank you for testing the new commit! I'll get the fixed version uploaded a.s.a.p. Please let me know if you encounter any more server crash bugs!

(I had intended to post this comment earlier but never got the chance to. 😅  )
